version: "2"
services:
    nginx:
        image: nginx
        container_name: my-nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./log/nginx/:/var/log/nginx
            - ./www/:/var/www:rw
    mysql:
        image: mysql:5.6
        container_name: my-mysql
        ports:
            - "3306:3306"
        volumes:
            - ./log/mysql/:/var/log/mysql:rw
            - ./mysql/:/var/lib/mysql:rw
        environment:
            MYSQL_ROOT_PASSWORD: "root"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: my-phpmyadmin
        ports:
            - "8080:80"
        environment:
            PMA_HOST: my-mysql
            MYSQL_ROOT_PASSWORD: "root"
