version: "2"
services:
    nginx:
        image: nginx
        ports:
            - "8080:80"
            - "443:443"
        volumes:
            - ./log/nginx/:/var/log/nginx
            - ./www/:/var/www:rw
